{{- if .Values.gotenberg.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "docshare.fullname" . }}-gotenberg
  labels:
    {{- include "docshare.labels" . | nindent 4 }}
    app.kubernetes.io/component: gotenberg
spec:
  type: {{ .Values.gotenberg.service.type }}
  ports:
    - port: {{ .Values.gotenberg.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "docshare.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: gotenberg
{{- end }}
